-- AlterTable
ALTER TABLE "cities" ADD COLUMN     "meal_budget" INTEGER NOT NULL DEFAULT 400,
ADD COLUMN     "meal_luxury" INTEGER NOT NULL DEFAULT 2200,
ADD COLUMN     "meal_mid" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN     "peak_months" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "stay_budget" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "stay_luxury" INTEGER NOT NULL DEFAULT 9000,
ADD COLUMN     "stay_mid" INTEGER NOT NULL DEFAULT 3500;
